// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sifsutnuuvadnxhfdcto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpZnN1dG51dXZhZG54aGZkY3RvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzOTc4MTAsImV4cCI6MjA2Mzk3MzgxMH0.Wgb7rhuc8J-umO4mX1NPFfFR5Upp5HWiyQCH7KY8Tq4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);